name: "Test"
on:
  pull_request:
  push:
  schedule:
    # every sunday morning
    - cron: "0 0 * * 0"
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # , macos-latest
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: build wot++ version
      run: nix-build --out-link wotpp wotpp.nix
    - name: build j2cli version
      run: nix-build --out-link j2cli j2cli.nix
    - name: build wordswurst version
      run: nix-build --out-link wordswurst wordswurst.nix
    - name: Move results to artifacts
      run: |
        mkdir -p artifacts/wotpp artifacts/j2cli artifacts/wordswurst
        cp wotpp/* artifacts/wotpp/
        cp j2cli/* artifacts/j2cli/
        cp wordswurst/* artifacts/wordswurst/
    - name: Generate diffs
      # TODO: diff wordswurst once it works
      run: |
        for doc in manpage.1 manpage.1.txt markdown.md strings.py; do
          diff -u j2cli/$doc wotpp/$doc > artifacts/$doc.j2-wpp.diff || true
          diff -u wotpp/$doc wordswurst/$doc > artifacts/$doc.wpp-wwst.diff || true
          echo "==== diff -u j2cli/$doc wotpp/$doc ===="
          cat artifacts/$doc.j2-wpp.diff
          echo "==== diff -u wotpp/$doc wordswurst/$doc ===="
          cat artifacts/$doc.wpp-wwst.diff
        done
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: artifacts
